### ISSUE TITLE
ERROR:  While executing gem ... (Gem::FilePermissionError)

### ISSUE THREAD

**Issue by DreamPWJ** [icyleaf/app_info#43]
执行gem install 报错 
```
liming@limingdeMac-mini cocoapods % sudo gem install app-info
Password:
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin21/rbconfig.rb:230: warning: Insecure world writable dir /opt/homebrew in PATH, mode 040777
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0 directory.

```

**Comment by DreamPWJ** [comment]
不支持Ruby3.0吗？

**Comment by icyleaf** [comment]
错误都给你提示啥问题了，你非要瞎想那怨谁呢

```
Insecure world writable dir /opt/homebrew in PATH, mode 040777
You don't have write permissions for the /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0 directory.
```

**Comment by DreamPWJ** [comment]
写错了

**Comment by DreamPWJ** [comment]
```
17:30:30  + ruby /Users/liming/jenkins/jenkins/workspace/test-android-app/ci/_jenkins/fastlane/actions/app_info.rb app/build/outputs/apk/atkj/debug/com.antai.property_DEBUG_5.1.3_2022-01-06_atkj.apk app_info.txt
17:30:30  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin21/rbconfig.rb:230: warning: Insecure world writable dir /opt/homebrew in PATH, mode 040777
17:30:30  /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- google/protobuf_c (LoadError)
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
17:30:30  	from /Users/liming/.gem/ruby/2.6.0/gems/google-protobuf-3.18.2-universal-darwin/lib/google/protobuf.rb:51:in `rescue in <top (required)>'
17:30:30  	from /Users/liming/.gem/ruby/2.6.0/gems/google-protobuf-3.18.2-universal-darwin/lib/google/protobuf.rb:48:in `<top (required)>'
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
17:30:30  	from /Users/liming/.gem/ruby/2.6.0/gems/app-info-2.8.1/lib/app_info/protobuf/models/Resources_pb.rb:4:in `<top (required)>'
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
17:30:30  	from /Users/liming/.gem/ruby/2.6.0/gems/app-info-2.8.1/lib/app_info/protobuf/manifest.rb:3:in `<top (required)>'
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
17:30:30  	from /Users/liming/.gem/ruby/2.6.0/gems/app-info-2.8.1/lib/app_info/aab.rb:3:in `<top (required)>'
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
17:30:30  	from /Users/liming/.gem/ruby/2.6.0/gems/app-info-2.8.1/lib/app_info.rb:16:in `<top (required)>'
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:148:in `require'
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:148:in `require'
17:30:30  	from /Users/liming/.gem/ruby/2.6.0/gems/app-info-2.8.1/lib/app-info.rb:3:in `<top (required)>'
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:160:in `require'
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:160:in `rescue in require'
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:149:in `require'
17:30:30  	from /Users/liming/jenkins/jenkins/workspace/test-android-app/ci/_jenkins/fastlane/actions/app_info.rb:4:in `<main>'
17:30:30  /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require': dlopen(/Users/liming/.gem/ruby/2.6.0/gems/google-protobuf-3.18.2-universal-darwin/lib/google/2.6/protobuf_c.bundle, 0x0009): tried: '/Users/liming/.gem/ruby/2.6.0/gems/google-protobuf-3.18.2-universal-darwin/lib/google/2.6/protobuf_c.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/protobuf_c.bundle' (no such file) - /Users/liming/.gem/ruby/2.6.0/gems/google-protobuf-3.18.2-universal-darwin/lib/google/2.6/protobuf_c.bundle (LoadError)
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
17:30:30  	from /Users/liming/.gem/ruby/2.6.0/gems/google-protobuf-3.18.2-universal-darwin/lib/google/protobuf.rb:49:in `<top (required)>'
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
17:30:30  	from /Users/liming/.gem/ruby/2.6.0/gems/app-info-2.8.1/lib/app_info/protobuf/models/Resources_pb.rb:4:in `<top (required)>'
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
17:30:30  	from /Users/liming/.gem/ruby/2.6.0/gems/app-info-2.8.1/lib/app_info/protobuf/manifest.rb:3:in `<top (required)>'
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
17:30:30  	from /Users/liming/.gem/ruby/2.6.0/gems/app-info-2.8.1/lib/app_info/aab.rb:3:in `<top (required)>'
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
17:30:30  	from /Users/liming/.gem/ruby/2.6.0/gems/app-info-2.8.1/lib/app_info.rb:16:in `<top (required)>'
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:148:in `require'
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:148:in `require'
17:30:30  	from /Users/liming/.gem/ruby/2.6.0/gems/app-info-2.8.1/lib/app-info.rb:3:in `<top (required)>'
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:160:in `require'
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:160:in `rescue in require'
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:149:in `require'
17:30:30  	from /Users/liming/jenkins/jenkins/workspace/test-android-app/ci/_jenkins/fastlane/actions/app_info.rb:4:in `<main>'
17:30:30  /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- app-info (LoadError)
17:30:30  	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
17:30:30  	from /Users/liming/jenkins/jenkins/workspace/test-android-app/ci/_jenkins/fastlane/actions/app_info.rb:4:in `<main>'
```

**Comment by icyleaf** [comment]
下面的报错都没找到 app-info 明显是没有正确安装

**Comment by icyleaf** [comment]
建议你使用 rvm、rbenv、asdf 来做 ruby 版本的管理或者使用 brew 的 ruby 版本，不太建议使用系统自带的 ruby

**Comment by DreamPWJ** [comment]
rvmf 这些版本管理在jenkins上面是无法识别的，识别出来的还是系统的ruby版本，我是用brew升级的ruby版本

**Comment by icyleaf** [comment]
rvm 有一个 jenkins 的插件，如果不用的话其实也行，设置下 rvm 安装的 ruby bin 和 gem bin 路径到 PATH 即可

**Comment by DreamPWJ** [comment]
> rvm 有一个 jenkins 的插件，如果不用的话其实也行，设置下 rvm 安装的 ruby bin 和 gem bin 路径到 PATH 即可

可以吗  rvm插件找了好多基本都不维护了，设置PATH了好多次都不起作用，一直是获取系统自带的ruby版本， 通过啥命令获取这两个路径啊

**Comment by icyleaf** [comment]
https://rvm.io/integration/jenkins

**Comment by DreamPWJ** [comment]
> https://rvm.io/integration/jenkins

现在我用的是brew升级的ruby版本 ，其他gem install下载的都好用，唯独app-info这个不好用啊

**Comment by icyleaf** [comment]
```diff
❯ brew install ruby
==> Downloading https://ghcr.io/v2/homebrew/core/ruby/manifests/3.0.3
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/ruby/blobs/sha256:dbb88009bf28a89e2685a81efb5a43a5b1821dcd0b8d220467f4e9eadb2082b8
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:dbb88009bf28a89e2685a81efb5a43a5b1821dcd0b8d220467f4e9eadb2082b8?se=2022-01-07T05%3A50%3A00Z&sig=j6cZUjLqZMRBd7Gbcq6PxG1oCB1izwDoyELdLbQnklk%3D&sp=r&spr=https&sr=b&sv=2019-12-12
######################################################################## 100.0%
==> Pouring ruby--3.0.3.big_sur.bottle.tar.gz
==> Caveats
By default, binaries installed by gem will be placed into:
  /usr/local/lib/ruby/gems/3.0.0/bin

You may want to add this to your PATH.

ruby is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have ruby first in your PATH, run:
+  echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.zshrc

For compilers to find ruby you may need to set:
  export LDFLAGS="-L/usr/local/opt/ruby/lib"
  export CPPFLAGS="-I/usr/local/opt/ruby/include"

For pkg-config to find ruby you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/ruby/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/ruby/3.0.3: 16,540 files, 39.4MB
==> Running `brew cleanup ruby`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

**Comment by DreamPWJ** [comment]
正确路径应该在 /opt/homebrew/lib/ruby/gems/3.0.0/bin      上面两个都无效， 关键现在只有app-info不能用，其他的都是好的

**Comment by icyleaf** [comment]
我没有 Arm 芯片的 macOS  🤣

**Comment by DreamPWJ** [comment]
虽然有点过分但是能否开发一个js版本的，可能更通用点，ruby周围几乎没用的

**Comment by DreamPWJ** [comment]
Ignoring google-protobuf-3.18.2 because its extensions are not built. Try: gem pristine google-protobuf --version 3.18.2
google-protobuf  还是有兼容性问题啊 版本一定固定了还是不行

**Comment by DreamPWJ** [comment]
已经准备切换到https://github.com/chenquincy/app-info-parser 这个了看看再说，ruby版本坑太多了，对不住了， 浪费太多时间了

**Comment by icyleaf** [comment]
你试试先用 brew 安装下 protobuf 在安装 app-info:

```
brew install protobuf
```

**Comment by icyleaf** [comment]
> 已经准备切换到https://github.com/chenquincy/app-info-parser 这个了看看再说，ruby版本坑太多了，对不住了， 浪费太多时间了

好的呢

**Comment by DreamPWJ** [comment]
抱歉了https://github.com/chenquincy/app-info-parser  已集成成功

**Comment by icyleaf** [comment]
找到你适合的就行
